version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk-browsers
    branches:
      only:
        - master
        - dev
    steps:
      - checkout
      - restore_cache:
          key: hotspot-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          key: hotspot-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/hotspot-0.0.1-SNAPSHOT.war