/*
 * This file is generated by jOOQ.
 */
package name.matco.hotspot.model.jooq;


import java.util.Arrays;
import java.util.List;

import name.matco.hotspot.model.jooq.tables.RevokedToken;
import name.matco.hotspot.model.jooq.tables.Spot;
import name.matco.hotspot.model.jooq.tables.Stash;
import name.matco.hotspot.model.jooq.tables.StashSpot;
import name.matco.hotspot.model.jooq.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>DEFAULT_SCHEMA</code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * The table <code>revoked_token</code>.
	 */
	public final RevokedToken REVOKED_TOKEN = RevokedToken.REVOKED_TOKEN;

	/**
	 * The table <code>spot</code>.
	 */
	public final Spot SPOT = Spot.SPOT;

	/**
	 * The table <code>stash</code>.
	 */
	public final Stash STASH = Stash.STASH;

	/**
	 * The table <code>stash_spot</code>.
	 */
	public final StashSpot STASH_SPOT = StashSpot.STASH_SPOT;

	/**
	 * The table <code>users</code>.
	 */
	public final Users USERS = Users.USERS;

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("", null);
	}


	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.asList(
			RevokedToken.REVOKED_TOKEN,
			Spot.SPOT,
			Stash.STASH,
			StashSpot.STASH_SPOT,
			Users.USERS
		);
	}
}
