/*
 * This file is generated by jOOQ.
 */
package name.matco.hotspot.model.jooq;


import name.matco.hotspot.model.jooq.tables.RevokedToken;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

	// -------------------------------------------------------------------------
	// INDEX definitions
	// -------------------------------------------------------------------------

	public static final Index REVOKED_TOKEN_REVOKED_TOKEN_USER = Internal.createIndex(DSL.name("revoked_token_user"), RevokedToken.REVOKED_TOKEN, new OrderField[] { RevokedToken.REVOKED_TOKEN.USER_FK }, false);
}
