/*
 * This file is generated by jOOQ.
 */
package name.matco.hotspot.model.jooq;


import name.matco.hotspot.model.jooq.tables.RevokedToken;
import name.matco.hotspot.model.jooq.tables.Spot;
import name.matco.hotspot.model.jooq.tables.Stash;
import name.matco.hotspot.model.jooq.tables.StashSpot;
import name.matco.hotspot.model.jooq.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

	/**
	 * The table <code>revoked_token</code>.
	 */
	public static final RevokedToken REVOKED_TOKEN = RevokedToken.REVOKED_TOKEN;

	/**
	 * The table <code>spot</code>.
	 */
	public static final Spot SPOT = Spot.SPOT;

	/**
	 * The table <code>stash</code>.
	 */
	public static final Stash STASH = Stash.STASH;

	/**
	 * The table <code>stash_spot</code>.
	 */
	public static final StashSpot STASH_SPOT = StashSpot.STASH_SPOT;

	/**
	 * The table <code>users</code>.
	 */
	public static final Users USERS = Users.USERS;
}
