/*
 * This file is generated by jOOQ.
 */
package name.matco.hotspot.model.jooq.tables;


import java.time.ZonedDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import name.matco.hotspot.model.jooq.DefaultSchema;
import name.matco.hotspot.model.jooq.Keys;
import name.matco.hotspot.model.jooq.tables.StashSpot.StashSpotPath;
import name.matco.hotspot.model.jooq.tables.Users.UsersPath;
import name.matco.hotspot.model.jooq.tables.records.StashRecord;
import name.matco.hotspot.services.jooq.configuration.DateConverter;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Stash extends TableImpl<StashRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>stash</code>
	 */
	public static final Stash STASH = new Stash();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StashRecord> getRecordType() {
		return StashRecord.class;
	}

	/**
	 * The column <code>stash.pk</code>.
	 */
	public final TableField<StashRecord, Integer> PK = createField(DSL.name("pk"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>stash.user_fk</code>.
	 */
	public final TableField<StashRecord, Integer> USER_FK = createField(DSL.name("user_fk"), SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>stash.uuid</code>.
	 */
	public final TableField<StashRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(64).nullable(false), this, "");

	/**
	 * The column <code>stash.creation_date</code>.
	 */
	public final TableField<StashRecord, ZonedDateTime> CREATION_DATE = createField(DSL.name("creation_date"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

	/**
	 * The column <code>stash.modification_date</code>.
	 */
	public final TableField<StashRecord, ZonedDateTime> MODIFICATION_DATE = createField(DSL.name("modification_date"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

	/**
	 * The column <code>stash.name</code>.
	 */
	public final TableField<StashRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>stash.description</code>.
	 */
	public final TableField<StashRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	private Stash(Name alias, Table<StashRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Stash(Name alias, Table<StashRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>stash</code> table reference
	 */
	public Stash(String alias) {
		this(DSL.name(alias), STASH);
	}

	/**
	 * Create an aliased <code>stash</code> table reference
	 */
	public Stash(Name alias) {
		this(alias, STASH);
	}

	/**
	 * Create a <code>stash</code> table reference
	 */
	public Stash() {
		this(DSL.name("stash"), null);
	}

	public <O extends Record> Stash(Table<O> path, ForeignKey<O, StashRecord> childPath, InverseForeignKey<O, StashRecord> parentPath) {
		super(path, childPath, parentPath, STASH);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class StashPath extends Stash implements Path<StashRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> StashPath(Table<O> path, ForeignKey<O, StashRecord> childPath, InverseForeignKey<O, StashRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private StashPath(Name alias, Table<StashRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public StashPath as(String alias) {
			return new StashPath(DSL.name(alias), this);
		}

		@Override
		public StashPath as(Name alias) {
			return new StashPath(alias, this);
		}

		@Override
		public StashPath as(Table<?> alias) {
			return new StashPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<StashRecord, Integer> getIdentity() {
		return (Identity<StashRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<StashRecord> getPrimaryKey() {
		return Keys.KEY_STASH_PRIMARY;
	}

	@Override
	public List<UniqueKey<StashRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_STASH_STASH_UUID);
	}

	@Override
	public List<ForeignKey<StashRecord, ?>> getReferences() {
		return Arrays.asList(Keys.STASH_USER);
	}

	private transient UsersPath _users;

	/**
	 * Get the implicit join path to the <code>hotspot.users</code> table.
	 */
	public UsersPath users() {
		if (_users == null)
			_users = new UsersPath(this, Keys.STASH_USER, null);

		return _users;
	}

	private transient StashSpotPath _stashSpot;

	/**
	 * Get the implicit to-many join path to the <code>hotspot.stash_spot</code>
	 * table
	 */
	public StashSpotPath stashSpot() {
		if (_stashSpot == null)
			_stashSpot = new StashSpotPath(this, null, Keys.STASH.getInverseKey());

		return _stashSpot;
	}

	@Override
	public Stash as(String alias) {
		return new Stash(DSL.name(alias), this);
	}

	@Override
	public Stash as(Name alias) {
		return new Stash(alias, this);
	}

	@Override
	public Stash as(Table<?> alias) {
		return new Stash(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Stash rename(String name) {
		return new Stash(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Stash rename(Name name) {
		return new Stash(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Stash rename(Table<?> name) {
		return new Stash(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Stash where(Condition condition) {
		return new Stash(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Stash where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Stash where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Stash where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Stash where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Stash where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Stash where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Stash where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Stash whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Stash whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
