/*
 * This file is generated by jOOQ.
 */
package name.matco.hotspot.model.jooq.tables.records;


import java.time.ZonedDateTime;

import name.matco.hotspot.model.jooq.tables.Users;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>users.pk</code>.
	 */
	public void setPk(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>users.pk</code>.
	 */
	public Integer getPk() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>users.creation_date</code>.
	 */
	public void setCreationDate(ZonedDateTime value) {
		set(1, value);
	}

	/**
	 * Getter for <code>users.creation_date</code>.
	 */
	public ZonedDateTime getCreationDate() {
		return (ZonedDateTime) get(1);
	}

	/**
	 * Setter for <code>users.modification_date</code>.
	 */
	public void setModificationDate(ZonedDateTime value) {
		set(2, value);
	}

	/**
	 * Getter for <code>users.modification_date</code>.
	 */
	public ZonedDateTime getModificationDate() {
		return (ZonedDateTime) get(2);
	}

	/**
	 * Setter for <code>users.handle</code>.
	 */
	public void setHandle(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>users.handle</code>.
	 */
	public String getHandle() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>users.name</code>.
	 */
	public void setName(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>users.name</code>.
	 */
	public String getName() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>users.email</code>.
	 */
	public void setEmail(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>users.email</code>.
	 */
	public String getEmail() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>users.password</code>.
	 */
	public void setPassword(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>users.password</code>.
	 */
	public String getPassword() {
		return (String) get(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(Integer pk, ZonedDateTime creationDate, ZonedDateTime modificationDate, String handle, String name_, String email, String password) {
		super(Users.USERS);

		setPk(pk);
		setCreationDate(creationDate);
		setModificationDate(modificationDate);
		setHandle(handle);
		setName(name_);
		setEmail(email);
		setPassword(password);
		resetChangedOnNotNull();
	}
}
