name: Test

permissions:
  contents: read

# this will be executed on every push on a branch (hence on every commit), but not when pushing a tag
on:
  push:
    branches:
      - '*'

jobs:
  package:
    name: Test package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Download application dependencies
        run: mvn -B dependency:go-offline --batch-mode
      - name: Check style of codebase
        shell: bash
        run: mvn -B checkstyle:check
      - name: Create application package
        run: mvn -B package
      - name: Store test reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: target/surefire-reports

      # generate and transform coverage report
      - name: Generate coverage report
        shell: bash
        run: mvn jacoco:report
      - name: Transform coverage report to PDF
        uses: LukaszLapaj/html-to-pdf-action@master
        with:
          htmlFile: target/site/jacoco/index.html
          outputFile: coverage-report.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
